# Generated by Django 3.2.8 on 2022-01-31 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20211112_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.event'),
        ),
    ]
